"""empty message

Revision ID: 273c0eb5b0ec
Revises: 
Create Date: 2024-10-21 11:52:41.762865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '273c0eb5b0ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movies')
    # ### end Alembic commands ###
